# -*- coding: utf-8 -*-
"""PrakAlgo[8]

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_YPhvIHXHChtvpIIOJ5G47XsRHwbhF5f
"""

print('@@@@ @@   @ @@@@@  @@@@  @@@@@@ @       @')
print('@  @ @ @  @ @    @ @   @ @      @       @')
print('@@@@ @  @ @ @    @ @   @ @@@@@@ @   @   @')
print('@  @ @   @@ @    @ @@@@  @      @   @   @')
print('@  @ @    @ @@@@@  @   @ @@@@@@ @@@@@@@@@')
def index_ganjil(kata):
    return kata[1::2]
input_kata = input("Masukkan sebuah kata: ")
hasil = index_ganjil(input_kata)
print("Karakter Index Ganjil:", hasil)

angka_pertama = int(input("Masukkan angka pertama: "))
angka_kedua = int(input("Masukkan angka kedua: "))
jumlah_range = sum(range(angka_pertama, angka_kedua + 1))

print("Jumlah range adalah:", jumlah_range)

